print "Starting maya loading and fbx conversion \n";
	
if (`file -q -exists "/Users/Anna/Desktop/Studium/Master/Semester4/AugmentedReality/HelloWorldAR/Assets/Prefabs/Ring.mb"`)
{		
	file -o "/Users/Anna/Desktop/Studium/Master/Semester4/AugmentedReality/HelloWorldAR/Assets/Prefabs/Ring.mb";
	FBXExportEmbeddedTextures -v false;
	// FBXExportHardEdges -v true;
	FBXExportApplyConstantKeyReducer -v false;
	FBXExportShowUI -v false;

	print "Before fbx export\n";
	FBXExport -f "/Users/Anna/Desktop/Studium/Master/Semester4/AugmentedReality/HelloWorldAR/Temp/ExportedFBXFile.fbx";
	print "after fbx export\n";
}
else
	print "Could not open Maya file.";

sysFile -delete "/Users/Anna/Desktop/Studium/Master/Semester4/AugmentedReality/HelloWorldAR/Temp/CommandPipe";

$donepipeKill = `fopen "/Users/Anna/Desktop/Studium/Master/Semester4/AugmentedReality/HelloWorldAR/Temp/SyncPipeKill" "w"`;
fwrite $donepipeKill "Done";
fclose $donepipeKill;
